baseURL = "https://codersfriend.github.io"
languageCode = "en-us"
title = "Codersfriend"

theme = "after-dark"


[[menu.main]]
  name = "Home"
  weight = 1
  identifier = "home"
  url = "/"
[[menu.main]]
  name = "Blog"
  weight = 2
  identifier = "blog"
  url = "/blog/"


[params]
  related_content_limit = 5

[permalinks]
  post = "/:section/:year/:month/:title/"
  blog = "/:section/:year/:month/:title/"